name: Validate Changes
on: [push]
jobs:
  setup-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketplace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('marketplace/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: npm ci
  Build-Marketplace:
    needs: setup-job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketplace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - name: Build Marketplace
        run: npm run build
  Unit-Test-Marketplace:
    needs: setup-job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketplace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: npm run test
  E2E-Test-Marketplace:
    needs: setup-job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./marketplace
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run e2e:test:ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30